#ifndef EFFECTDEMO_BEFEPLATFORMDEFINE_H
#define EFFECTDEMO_BEFEPLATFORMDEFINE_H

#define NAMESPACE_BEF_EFFECT_FRAMEWORK_BEGIN namespace BEF {
#define NAMESPACE_BEF_EFFECT_FRAMEWORK_END }

#define BEF_EFFECT_PLATFORM_WINDOWS    1
#define BEF_EFFECT_PLATFORM_MAC        2
#define BEF_EFFECT_PLATFORM_IOS        3
#define BEF_EFFECT_PLATFORM_ANDROID    4
#define BEF_EFFECT_PLATFORM_LINUX      5
#define BEF_EFFECT_PLATFORM_WASM       6
#define BEF_EFFECT_PLATFORM_UNKNOWN    7

#if defined(__EMSCRIPTEN__)
#   define BEF_EFFECT_PLATFORM BEF_EFFECT_PLATFORM_WASM
#elif defined(__APPLE__)
#   include <TargetConditionals.h>
#   if TARGET_OS_IPHONE || TARGET_IPHONE_SIMULATOR
#       define BEF_EFFECT_PLATFORM BEF_EFFECT_PLATFORM_IOS
#   elif TARGET_OS_OSX
#       define BEF_EFFECT_PLATFORM BEF_EFFECT_PLATFORM_MAC
#   endif
#elif defined(__ANDROID__)
#   define BEF_EFFECT_PLATFORM BEF_EFFECT_PLATFORM_ANDROID
#elif defined(__linux__)
#   define BEF_EFFECT_PLATFORM BEF_EFFECT_PLATFORM_LINUX
#elif defined(_MSC_VER)
#   define BEF_EFFECT_PLATFORM BEF_EFFECT_PLATFORM_WINDOWS
#else
#   define BEF_EFFECT_PLATFORM BEF_EFFECT_PLATFORM_UNKNOWN
#endif

#endif
