#pragma once

enum RTC_EVENT_TYPE {
	RTC_EVENT_ERROR,
	RTC_EVENT_WARNING,
	RTC_EVENT_ENTERROOM_RESULT,
	RTC_EVENT_EXITROOM_RESULT,
	RTC_EVENT_REMOTE_USER_ENTER,
	RTC_EVENT_REMOTE_USER_LEAVE,
	RTC_EVENT_USER_AUDIO_AVAILABLE,
	RTC_EVENT_SWITCH_ROOM,
	RTC_EVENT_USER_VIDEO_AVAILABLE,
};
